# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/slavamuravey/projects/learn/my-own-libuv

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/slavamuravey/projects/learn/my-own-libuv

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/slavamuravey/projects/learn/my-own-libuv/CMakeFiles /home/slavamuravey/projects/learn/my-own-libuv//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/slavamuravey/projects/learn/my-own-libuv/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named helloworld

# Build rule for target.
helloworld: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 helloworld
.PHONY : helloworld

# fast build rule for target.
helloworld/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/build
.PHONY : helloworld/fast

examples/helloworld/main.o: examples/helloworld/main.c.o
.PHONY : examples/helloworld/main.o

# target to build an object file
examples/helloworld/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/examples/helloworld/main.c.o
.PHONY : examples/helloworld/main.c.o

examples/helloworld/main.i: examples/helloworld/main.c.i
.PHONY : examples/helloworld/main.i

# target to preprocess a source file
examples/helloworld/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/examples/helloworld/main.c.i
.PHONY : examples/helloworld/main.c.i

examples/helloworld/main.s: examples/helloworld/main.c.s
.PHONY : examples/helloworld/main.s

# target to generate assembly for a file
examples/helloworld/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/examples/helloworld/main.c.s
.PHONY : examples/helloworld/main.c.s

src/async.o: src/async.c.o
.PHONY : src/async.o

# target to build an object file
src/async.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/async.c.o
.PHONY : src/async.c.o

src/async.i: src/async.c.i
.PHONY : src/async.i

# target to preprocess a source file
src/async.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/async.c.i
.PHONY : src/async.c.i

src/async.s: src/async.c.s
.PHONY : src/async.s

# target to generate assembly for a file
src/async.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/async.c.s
.PHONY : src/async.c.s

src/core.o: src/core.c.o
.PHONY : src/core.o

# target to build an object file
src/core.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/core.c.o
.PHONY : src/core.c.o

src/core.i: src/core.c.i
.PHONY : src/core.i

# target to preprocess a source file
src/core.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/core.c.i
.PHONY : src/core.c.i

src/core.s: src/core.c.s
.PHONY : src/core.s

# target to generate assembly for a file
src/core.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/core.c.s
.PHONY : src/core.c.s

src/dl.o: src/dl.c.o
.PHONY : src/dl.o

# target to build an object file
src/dl.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/dl.c.o
.PHONY : src/dl.c.o

src/dl.i: src/dl.c.i
.PHONY : src/dl.i

# target to preprocess a source file
src/dl.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/dl.c.i
.PHONY : src/dl.c.i

src/dl.s: src/dl.c.s
.PHONY : src/dl.s

# target to generate assembly for a file
src/dl.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/dl.c.s
.PHONY : src/dl.c.s

src/fs-poll.o: src/fs-poll.c.o
.PHONY : src/fs-poll.o

# target to build an object file
src/fs-poll.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/fs-poll.c.o
.PHONY : src/fs-poll.c.o

src/fs-poll.i: src/fs-poll.c.i
.PHONY : src/fs-poll.i

# target to preprocess a source file
src/fs-poll.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/fs-poll.c.i
.PHONY : src/fs-poll.c.i

src/fs-poll.s: src/fs-poll.c.s
.PHONY : src/fs-poll.s

# target to generate assembly for a file
src/fs-poll.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/fs-poll.c.s
.PHONY : src/fs-poll.c.s

src/fs.o: src/fs.c.o
.PHONY : src/fs.o

# target to build an object file
src/fs.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/fs.c.o
.PHONY : src/fs.c.o

src/fs.i: src/fs.c.i
.PHONY : src/fs.i

# target to preprocess a source file
src/fs.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/fs.c.i
.PHONY : src/fs.c.i

src/fs.s: src/fs.c.s
.PHONY : src/fs.s

# target to generate assembly for a file
src/fs.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/fs.c.s
.PHONY : src/fs.c.s

src/getaddrinfo.o: src/getaddrinfo.c.o
.PHONY : src/getaddrinfo.o

# target to build an object file
src/getaddrinfo.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/getaddrinfo.c.o
.PHONY : src/getaddrinfo.c.o

src/getaddrinfo.i: src/getaddrinfo.c.i
.PHONY : src/getaddrinfo.i

# target to preprocess a source file
src/getaddrinfo.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/getaddrinfo.c.i
.PHONY : src/getaddrinfo.c.i

src/getaddrinfo.s: src/getaddrinfo.c.s
.PHONY : src/getaddrinfo.s

# target to generate assembly for a file
src/getaddrinfo.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/getaddrinfo.c.s
.PHONY : src/getaddrinfo.c.s

src/getnameinfo.o: src/getnameinfo.c.o
.PHONY : src/getnameinfo.o

# target to build an object file
src/getnameinfo.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/getnameinfo.c.o
.PHONY : src/getnameinfo.c.o

src/getnameinfo.i: src/getnameinfo.c.i
.PHONY : src/getnameinfo.i

# target to preprocess a source file
src/getnameinfo.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/getnameinfo.c.i
.PHONY : src/getnameinfo.c.i

src/getnameinfo.s: src/getnameinfo.c.s
.PHONY : src/getnameinfo.s

# target to generate assembly for a file
src/getnameinfo.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/getnameinfo.c.s
.PHONY : src/getnameinfo.c.s

src/idna.o: src/idna.c.o
.PHONY : src/idna.o

# target to build an object file
src/idna.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/idna.c.o
.PHONY : src/idna.c.o

src/idna.i: src/idna.c.i
.PHONY : src/idna.i

# target to preprocess a source file
src/idna.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/idna.c.i
.PHONY : src/idna.c.i

src/idna.s: src/idna.c.s
.PHONY : src/idna.s

# target to generate assembly for a file
src/idna.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/idna.c.s
.PHONY : src/idna.c.s

src/inet.o: src/inet.c.o
.PHONY : src/inet.o

# target to build an object file
src/inet.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/inet.c.o
.PHONY : src/inet.c.o

src/inet.i: src/inet.c.i
.PHONY : src/inet.i

# target to preprocess a source file
src/inet.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/inet.c.i
.PHONY : src/inet.c.i

src/inet.s: src/inet.c.s
.PHONY : src/inet.s

# target to generate assembly for a file
src/inet.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/inet.c.s
.PHONY : src/inet.c.s

src/linux.o: src/linux.c.o
.PHONY : src/linux.o

# target to build an object file
src/linux.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/linux.c.o
.PHONY : src/linux.c.o

src/linux.i: src/linux.c.i
.PHONY : src/linux.i

# target to preprocess a source file
src/linux.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/linux.c.i
.PHONY : src/linux.c.i

src/linux.s: src/linux.c.s
.PHONY : src/linux.s

# target to generate assembly for a file
src/linux.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/linux.c.s
.PHONY : src/linux.c.s

src/loop-watcher.o: src/loop-watcher.c.o
.PHONY : src/loop-watcher.o

# target to build an object file
src/loop-watcher.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/loop-watcher.c.o
.PHONY : src/loop-watcher.c.o

src/loop-watcher.i: src/loop-watcher.c.i
.PHONY : src/loop-watcher.i

# target to preprocess a source file
src/loop-watcher.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/loop-watcher.c.i
.PHONY : src/loop-watcher.c.i

src/loop-watcher.s: src/loop-watcher.c.s
.PHONY : src/loop-watcher.s

# target to generate assembly for a file
src/loop-watcher.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/loop-watcher.c.s
.PHONY : src/loop-watcher.c.s

src/loop.o: src/loop.c.o
.PHONY : src/loop.o

# target to build an object file
src/loop.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/loop.c.o
.PHONY : src/loop.c.o

src/loop.i: src/loop.c.i
.PHONY : src/loop.i

# target to preprocess a source file
src/loop.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/loop.c.i
.PHONY : src/loop.c.i

src/loop.s: src/loop.c.s
.PHONY : src/loop.s

# target to generate assembly for a file
src/loop.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/loop.c.s
.PHONY : src/loop.c.s

src/pipe.o: src/pipe.c.o
.PHONY : src/pipe.o

# target to build an object file
src/pipe.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/pipe.c.o
.PHONY : src/pipe.c.o

src/pipe.i: src/pipe.c.i
.PHONY : src/pipe.i

# target to preprocess a source file
src/pipe.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/pipe.c.i
.PHONY : src/pipe.c.i

src/pipe.s: src/pipe.c.s
.PHONY : src/pipe.s

# target to generate assembly for a file
src/pipe.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/pipe.c.s
.PHONY : src/pipe.c.s

src/poll.o: src/poll.c.o
.PHONY : src/poll.o

# target to build an object file
src/poll.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/poll.c.o
.PHONY : src/poll.c.o

src/poll.i: src/poll.c.i
.PHONY : src/poll.i

# target to preprocess a source file
src/poll.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/poll.c.i
.PHONY : src/poll.c.i

src/poll.s: src/poll.c.s
.PHONY : src/poll.s

# target to generate assembly for a file
src/poll.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/poll.c.s
.PHONY : src/poll.c.s

src/process.o: src/process.c.o
.PHONY : src/process.o

# target to build an object file
src/process.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/process.c.o
.PHONY : src/process.c.o

src/process.i: src/process.c.i
.PHONY : src/process.i

# target to preprocess a source file
src/process.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/process.c.i
.PHONY : src/process.c.i

src/process.s: src/process.c.s
.PHONY : src/process.s

# target to generate assembly for a file
src/process.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/process.c.s
.PHONY : src/process.c.s

src/procfs-exepath.o: src/procfs-exepath.c.o
.PHONY : src/procfs-exepath.o

# target to build an object file
src/procfs-exepath.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/procfs-exepath.c.o
.PHONY : src/procfs-exepath.c.o

src/procfs-exepath.i: src/procfs-exepath.c.i
.PHONY : src/procfs-exepath.i

# target to preprocess a source file
src/procfs-exepath.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/procfs-exepath.c.i
.PHONY : src/procfs-exepath.c.i

src/procfs-exepath.s: src/procfs-exepath.c.s
.PHONY : src/procfs-exepath.s

# target to generate assembly for a file
src/procfs-exepath.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/procfs-exepath.c.s
.PHONY : src/procfs-exepath.c.s

src/proctitle.o: src/proctitle.c.o
.PHONY : src/proctitle.o

# target to build an object file
src/proctitle.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/proctitle.c.o
.PHONY : src/proctitle.c.o

src/proctitle.i: src/proctitle.c.i
.PHONY : src/proctitle.i

# target to preprocess a source file
src/proctitle.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/proctitle.c.i
.PHONY : src/proctitle.c.i

src/proctitle.s: src/proctitle.c.s
.PHONY : src/proctitle.s

# target to generate assembly for a file
src/proctitle.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/proctitle.c.s
.PHONY : src/proctitle.c.s

src/random-devurandom.o: src/random-devurandom.c.o
.PHONY : src/random-devurandom.o

# target to build an object file
src/random-devurandom.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/random-devurandom.c.o
.PHONY : src/random-devurandom.c.o

src/random-devurandom.i: src/random-devurandom.c.i
.PHONY : src/random-devurandom.i

# target to preprocess a source file
src/random-devurandom.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/random-devurandom.c.i
.PHONY : src/random-devurandom.c.i

src/random-devurandom.s: src/random-devurandom.c.s
.PHONY : src/random-devurandom.s

# target to generate assembly for a file
src/random-devurandom.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/random-devurandom.c.s
.PHONY : src/random-devurandom.c.s

src/random-getentropy.o: src/random-getentropy.c.o
.PHONY : src/random-getentropy.o

# target to build an object file
src/random-getentropy.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/random-getentropy.c.o
.PHONY : src/random-getentropy.c.o

src/random-getentropy.i: src/random-getentropy.c.i
.PHONY : src/random-getentropy.i

# target to preprocess a source file
src/random-getentropy.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/random-getentropy.c.i
.PHONY : src/random-getentropy.c.i

src/random-getentropy.s: src/random-getentropy.c.s
.PHONY : src/random-getentropy.s

# target to generate assembly for a file
src/random-getentropy.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/random-getentropy.c.s
.PHONY : src/random-getentropy.c.s

src/random-getrandom.o: src/random-getrandom.c.o
.PHONY : src/random-getrandom.o

# target to build an object file
src/random-getrandom.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/random-getrandom.c.o
.PHONY : src/random-getrandom.c.o

src/random-getrandom.i: src/random-getrandom.c.i
.PHONY : src/random-getrandom.i

# target to preprocess a source file
src/random-getrandom.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/random-getrandom.c.i
.PHONY : src/random-getrandom.c.i

src/random-getrandom.s: src/random-getrandom.c.s
.PHONY : src/random-getrandom.s

# target to generate assembly for a file
src/random-getrandom.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/random-getrandom.c.s
.PHONY : src/random-getrandom.c.s

src/random-sysctl-linux.o: src/random-sysctl-linux.c.o
.PHONY : src/random-sysctl-linux.o

# target to build an object file
src/random-sysctl-linux.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/random-sysctl-linux.c.o
.PHONY : src/random-sysctl-linux.c.o

src/random-sysctl-linux.i: src/random-sysctl-linux.c.i
.PHONY : src/random-sysctl-linux.i

# target to preprocess a source file
src/random-sysctl-linux.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/random-sysctl-linux.c.i
.PHONY : src/random-sysctl-linux.c.i

src/random-sysctl-linux.s: src/random-sysctl-linux.c.s
.PHONY : src/random-sysctl-linux.s

# target to generate assembly for a file
src/random-sysctl-linux.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/random-sysctl-linux.c.s
.PHONY : src/random-sysctl-linux.c.s

src/random.o: src/random.c.o
.PHONY : src/random.o

# target to build an object file
src/random.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/random.c.o
.PHONY : src/random.c.o

src/random.i: src/random.c.i
.PHONY : src/random.i

# target to preprocess a source file
src/random.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/random.c.i
.PHONY : src/random.c.i

src/random.s: src/random.c.s
.PHONY : src/random.s

# target to generate assembly for a file
src/random.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/random.c.s
.PHONY : src/random.c.s

src/signal.o: src/signal.c.o
.PHONY : src/signal.o

# target to build an object file
src/signal.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/signal.c.o
.PHONY : src/signal.c.o

src/signal.i: src/signal.c.i
.PHONY : src/signal.i

# target to preprocess a source file
src/signal.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/signal.c.i
.PHONY : src/signal.c.i

src/signal.s: src/signal.c.s
.PHONY : src/signal.s

# target to generate assembly for a file
src/signal.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/signal.c.s
.PHONY : src/signal.c.s

src/stream.o: src/stream.c.o
.PHONY : src/stream.o

# target to build an object file
src/stream.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/stream.c.o
.PHONY : src/stream.c.o

src/stream.i: src/stream.c.i
.PHONY : src/stream.i

# target to preprocess a source file
src/stream.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/stream.c.i
.PHONY : src/stream.c.i

src/stream.s: src/stream.c.s
.PHONY : src/stream.s

# target to generate assembly for a file
src/stream.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/stream.c.s
.PHONY : src/stream.c.s

src/strscpy.o: src/strscpy.c.o
.PHONY : src/strscpy.o

# target to build an object file
src/strscpy.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/strscpy.c.o
.PHONY : src/strscpy.c.o

src/strscpy.i: src/strscpy.c.i
.PHONY : src/strscpy.i

# target to preprocess a source file
src/strscpy.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/strscpy.c.i
.PHONY : src/strscpy.c.i

src/strscpy.s: src/strscpy.c.s
.PHONY : src/strscpy.s

# target to generate assembly for a file
src/strscpy.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/strscpy.c.s
.PHONY : src/strscpy.c.s

src/strtok.o: src/strtok.c.o
.PHONY : src/strtok.o

# target to build an object file
src/strtok.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/strtok.c.o
.PHONY : src/strtok.c.o

src/strtok.i: src/strtok.c.i
.PHONY : src/strtok.i

# target to preprocess a source file
src/strtok.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/strtok.c.i
.PHONY : src/strtok.c.i

src/strtok.s: src/strtok.c.s
.PHONY : src/strtok.s

# target to generate assembly for a file
src/strtok.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/strtok.c.s
.PHONY : src/strtok.c.s

src/tcp.o: src/tcp.c.o
.PHONY : src/tcp.o

# target to build an object file
src/tcp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/tcp.c.o
.PHONY : src/tcp.c.o

src/tcp.i: src/tcp.c.i
.PHONY : src/tcp.i

# target to preprocess a source file
src/tcp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/tcp.c.i
.PHONY : src/tcp.c.i

src/tcp.s: src/tcp.c.s
.PHONY : src/tcp.s

# target to generate assembly for a file
src/tcp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/tcp.c.s
.PHONY : src/tcp.c.s

src/thread-common.o: src/thread-common.c.o
.PHONY : src/thread-common.o

# target to build an object file
src/thread-common.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/thread-common.c.o
.PHONY : src/thread-common.c.o

src/thread-common.i: src/thread-common.c.i
.PHONY : src/thread-common.i

# target to preprocess a source file
src/thread-common.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/thread-common.c.i
.PHONY : src/thread-common.c.i

src/thread-common.s: src/thread-common.c.s
.PHONY : src/thread-common.s

# target to generate assembly for a file
src/thread-common.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/thread-common.c.s
.PHONY : src/thread-common.c.s

src/thread.o: src/thread.c.o
.PHONY : src/thread.o

# target to build an object file
src/thread.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/thread.c.o
.PHONY : src/thread.c.o

src/thread.i: src/thread.c.i
.PHONY : src/thread.i

# target to preprocess a source file
src/thread.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/thread.c.i
.PHONY : src/thread.c.i

src/thread.s: src/thread.c.s
.PHONY : src/thread.s

# target to generate assembly for a file
src/thread.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/thread.c.s
.PHONY : src/thread.c.s

src/threadpool.o: src/threadpool.c.o
.PHONY : src/threadpool.o

# target to build an object file
src/threadpool.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/threadpool.c.o
.PHONY : src/threadpool.c.o

src/threadpool.i: src/threadpool.c.i
.PHONY : src/threadpool.i

# target to preprocess a source file
src/threadpool.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/threadpool.c.i
.PHONY : src/threadpool.c.i

src/threadpool.s: src/threadpool.c.s
.PHONY : src/threadpool.s

# target to generate assembly for a file
src/threadpool.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/threadpool.c.s
.PHONY : src/threadpool.c.s

src/timer.o: src/timer.c.o
.PHONY : src/timer.o

# target to build an object file
src/timer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/timer.c.o
.PHONY : src/timer.c.o

src/timer.i: src/timer.c.i
.PHONY : src/timer.i

# target to preprocess a source file
src/timer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/timer.c.i
.PHONY : src/timer.c.i

src/timer.s: src/timer.c.s
.PHONY : src/timer.s

# target to generate assembly for a file
src/timer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/timer.c.s
.PHONY : src/timer.c.s

src/tty.o: src/tty.c.o
.PHONY : src/tty.o

# target to build an object file
src/tty.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/tty.c.o
.PHONY : src/tty.c.o

src/tty.i: src/tty.c.i
.PHONY : src/tty.i

# target to preprocess a source file
src/tty.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/tty.c.i
.PHONY : src/tty.c.i

src/tty.s: src/tty.c.s
.PHONY : src/tty.s

# target to generate assembly for a file
src/tty.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/tty.c.s
.PHONY : src/tty.c.s

src/udp.o: src/udp.c.o
.PHONY : src/udp.o

# target to build an object file
src/udp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/udp.c.o
.PHONY : src/udp.c.o

src/udp.i: src/udp.c.i
.PHONY : src/udp.i

# target to preprocess a source file
src/udp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/udp.c.i
.PHONY : src/udp.c.i

src/udp.s: src/udp.c.s
.PHONY : src/udp.s

# target to generate assembly for a file
src/udp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/udp.c.s
.PHONY : src/udp.c.s

src/uv-common.o: src/uv-common.c.o
.PHONY : src/uv-common.o

# target to build an object file
src/uv-common.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/uv-common.c.o
.PHONY : src/uv-common.c.o

src/uv-common.i: src/uv-common.c.i
.PHONY : src/uv-common.i

# target to preprocess a source file
src/uv-common.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/uv-common.c.i
.PHONY : src/uv-common.c.i

src/uv-common.s: src/uv-common.c.s
.PHONY : src/uv-common.s

# target to generate assembly for a file
src/uv-common.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/uv-common.c.s
.PHONY : src/uv-common.c.s

src/uv-data-getter-setters.o: src/uv-data-getter-setters.c.o
.PHONY : src/uv-data-getter-setters.o

# target to build an object file
src/uv-data-getter-setters.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/uv-data-getter-setters.c.o
.PHONY : src/uv-data-getter-setters.c.o

src/uv-data-getter-setters.i: src/uv-data-getter-setters.c.i
.PHONY : src/uv-data-getter-setters.i

# target to preprocess a source file
src/uv-data-getter-setters.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/uv-data-getter-setters.c.i
.PHONY : src/uv-data-getter-setters.c.i

src/uv-data-getter-setters.s: src/uv-data-getter-setters.c.s
.PHONY : src/uv-data-getter-setters.s

# target to generate assembly for a file
src/uv-data-getter-setters.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/uv-data-getter-setters.c.s
.PHONY : src/uv-data-getter-setters.c.s

src/version.o: src/version.c.o
.PHONY : src/version.o

# target to build an object file
src/version.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/version.c.o
.PHONY : src/version.c.o

src/version.i: src/version.c.i
.PHONY : src/version.i

# target to preprocess a source file
src/version.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/version.c.i
.PHONY : src/version.c.i

src/version.s: src/version.c.s
.PHONY : src/version.s

# target to generate assembly for a file
src/version.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/version.c.s
.PHONY : src/version.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... helloworld"
	@echo "... examples/helloworld/main.o"
	@echo "... examples/helloworld/main.i"
	@echo "... examples/helloworld/main.s"
	@echo "... src/async.o"
	@echo "... src/async.i"
	@echo "... src/async.s"
	@echo "... src/core.o"
	@echo "... src/core.i"
	@echo "... src/core.s"
	@echo "... src/dl.o"
	@echo "... src/dl.i"
	@echo "... src/dl.s"
	@echo "... src/fs-poll.o"
	@echo "... src/fs-poll.i"
	@echo "... src/fs-poll.s"
	@echo "... src/fs.o"
	@echo "... src/fs.i"
	@echo "... src/fs.s"
	@echo "... src/getaddrinfo.o"
	@echo "... src/getaddrinfo.i"
	@echo "... src/getaddrinfo.s"
	@echo "... src/getnameinfo.o"
	@echo "... src/getnameinfo.i"
	@echo "... src/getnameinfo.s"
	@echo "... src/idna.o"
	@echo "... src/idna.i"
	@echo "... src/idna.s"
	@echo "... src/inet.o"
	@echo "... src/inet.i"
	@echo "... src/inet.s"
	@echo "... src/linux.o"
	@echo "... src/linux.i"
	@echo "... src/linux.s"
	@echo "... src/loop-watcher.o"
	@echo "... src/loop-watcher.i"
	@echo "... src/loop-watcher.s"
	@echo "... src/loop.o"
	@echo "... src/loop.i"
	@echo "... src/loop.s"
	@echo "... src/pipe.o"
	@echo "... src/pipe.i"
	@echo "... src/pipe.s"
	@echo "... src/poll.o"
	@echo "... src/poll.i"
	@echo "... src/poll.s"
	@echo "... src/process.o"
	@echo "... src/process.i"
	@echo "... src/process.s"
	@echo "... src/procfs-exepath.o"
	@echo "... src/procfs-exepath.i"
	@echo "... src/procfs-exepath.s"
	@echo "... src/proctitle.o"
	@echo "... src/proctitle.i"
	@echo "... src/proctitle.s"
	@echo "... src/random-devurandom.o"
	@echo "... src/random-devurandom.i"
	@echo "... src/random-devurandom.s"
	@echo "... src/random-getentropy.o"
	@echo "... src/random-getentropy.i"
	@echo "... src/random-getentropy.s"
	@echo "... src/random-getrandom.o"
	@echo "... src/random-getrandom.i"
	@echo "... src/random-getrandom.s"
	@echo "... src/random-sysctl-linux.o"
	@echo "... src/random-sysctl-linux.i"
	@echo "... src/random-sysctl-linux.s"
	@echo "... src/random.o"
	@echo "... src/random.i"
	@echo "... src/random.s"
	@echo "... src/signal.o"
	@echo "... src/signal.i"
	@echo "... src/signal.s"
	@echo "... src/stream.o"
	@echo "... src/stream.i"
	@echo "... src/stream.s"
	@echo "... src/strscpy.o"
	@echo "... src/strscpy.i"
	@echo "... src/strscpy.s"
	@echo "... src/strtok.o"
	@echo "... src/strtok.i"
	@echo "... src/strtok.s"
	@echo "... src/tcp.o"
	@echo "... src/tcp.i"
	@echo "... src/tcp.s"
	@echo "... src/thread-common.o"
	@echo "... src/thread-common.i"
	@echo "... src/thread-common.s"
	@echo "... src/thread.o"
	@echo "... src/thread.i"
	@echo "... src/thread.s"
	@echo "... src/threadpool.o"
	@echo "... src/threadpool.i"
	@echo "... src/threadpool.s"
	@echo "... src/timer.o"
	@echo "... src/timer.i"
	@echo "... src/timer.s"
	@echo "... src/tty.o"
	@echo "... src/tty.i"
	@echo "... src/tty.s"
	@echo "... src/udp.o"
	@echo "... src/udp.i"
	@echo "... src/udp.s"
	@echo "... src/uv-common.o"
	@echo "... src/uv-common.i"
	@echo "... src/uv-common.s"
	@echo "... src/uv-data-getter-setters.o"
	@echo "... src/uv-data-getter-setters.i"
	@echo "... src/uv-data-getter-setters.s"
	@echo "... src/version.o"
	@echo "... src/version.i"
	@echo "... src/version.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

